export const ASSET_PATH =
  '/model/KayKit_Skeletons_1.0_FREE/characters/gltf/{name}.glb';

export const ASSETS = [
  'Skeleton_Minion', // 1
];

export const ITEM_SIZE = 2;

export const DEFAULT_ACTION_NAME = 'Running_A';

export const GUI_VALUES = {
  actionName: 'Running_A',
  skeletonHelper: false,
};

export const GUI_OPTIONS = {
  ui: [
    { label: '动画名称', name: 'actionName', options: 'actions' },
    { label: '显示骨骼', name: 'skeletonHelper' },
  ],
  options: {
    actions: [
      '1H_Melee_Attack_Chop',
      '1H_Melee_Attack_Jump_Chop',
      '1H_Melee_Attack_Slice_Diagonal',
      '1H_Melee_Attack_Slice_Horizontal',
      '1H_Melee_Attack_Stab',
      '1H_Ranged_Aiming',
      '1H_Ranged_Reload',
      '1H_Ranged_Shoot',
      '1H_Ranged_Shooting',
      '2H_Melee_Attack_Chop',
      '2H_Melee_Attack_Slice',
      '2H_Melee_Attack_Spin',
      '2H_Melee_Attack_Spinning',
      '2H_Melee_Attack_Stab',
      '2H_Melee_Idle',
      '2H_Ranged_Aiming',
      '2H_Ranged_Reload',
      '2H_Ranged_Shoot',
      '2H_Ranged_Shooting',
      'Block',
      'Block_Attack',
      'Block_Hit',
      'Blocking',
      'Cheer',
      'Death_A',
      'Death_A_Pose',
      'Death_B',
      'Death_B_Pose',
      'Death_C_Pose',
      'Death_C_Skeletons',
      'Death_C_Skeletons_Resurrect',
      'Dodge_Backward',
      'Dodge_Forward',
      'Dodge_Left',
      'Dodge_Right',
      'Dualwield_Melee_Attack_Chop',
      'Dualwield_Melee_Attack_Slice',
      'Dualwield_Melee_Attack_Stab',
      'Hit_A',
      'Hit_B',
      'Idle',
      'Idle_B',
      'Idle_Combat',
      'Interact',
      'Jump_Full_Long',
      'Jump_Full_Short',
      'Jump_Idle',
      'Jump_Land',
      'Jump_Start',
      'Lie_Down',
      'Lie_Idle',
      'Lie_Pose',
      'Lie_StandUp',
      'PickUp',
      'Running_A',
      'Running_B',
      'Running_C',
      'Running_Strafe_Left',
      'Running_Strafe_Right',
      'Sit_Chair_Down',
      'Sit_Chair_Idle',
      'Sit_Chair_Pose',
      'Sit_Chair_StandUp',
      'Sit_Floor_Down',
      'Sit_Floor_Idle',
      'Sit_Floor_Pose',
      'Sit_Floor_StandUp',
      'Skeleton_Inactive_Standing_Pose',
      'Skeletons_Awaken_Floor',
      'Skeletons_Awaken_Floor_Long',
      'Skeletons_Awaken_Standing',
      'Skeletons_Inactive_Floor_Pose',
      'Spawn_Air',
      'Spawn_Ground',
      'Spawn_Ground_Skeletons',
      'Spellcast_Long',
      'Spellcast_Raise',
      'Spellcast_Shoot',
      'Spellcast_Summon',
      'Spellcasting',
      'T-Pose',
      'Taunt',
      'Taunt_Longer',
      'Throw',
      'Unarmed_Idle',
      'Unarmed_Melee_Attack_Kick',
      'Unarmed_Melee_Attack_Punch_A',
      'Unarmed_Melee_Attack_Punch_B',
      'Unarmed_Pose',
      'Use_Item',
      'Walking_A',
      'Walking_B',
      'Walking_Backwards',
      'Walking_C',
      'Walking_D_Skeletons',
    ],
  },
};
